* Подключение к удаленному лиспу
   
Одним из преимуществ SLIME заключается реализуется в том, что мы можем
легко запустить сторону Emacs (slime.el) на одной машине и LISP сервер
(swank) на другой.  Основная идея заключается в запуске Lisp на
удаленной машине, загрузке swank и ожидании входящих подключений от
SLIME.  На локальной машине мы запускаем Emacs и говорим SLIME
подключиться к удаленному компьютеру.  Подробностей несколько больше,
но основная описанная выше идея проста.

** Настройка образа Lisp на удаленном лисп-сервере

*** Запуск командного интерпретатора на удаленном сервере
$ssh namatv@mnasoft-pi

***** Запуск screen
$screen -R

**** Запуск лисп (ccl)
$ccl

******* Запуск серверной части SWANK
LISP> (require 'asdf) (asdf:oos 'asdf:load-op 'swank) (setf swank:*use-dedicated-output-stream* nil) (swank:create-server :port 4005  :dont-close t )

*** Выход из screen
C-a d

*** Выход из интерпретатора команд
$C-d

**** Машина с Emacs
****** Создание тоннеля
$ssh -2 -N -f -L 4005:localhost:4005 namatv@mnasoft-pi

******* Запуск emacs
$emacs

******* Подключение к удаленному серверу
M-x slime-connect
127.0.0.1
4005
