#!/bin/bash
#

if [[ `ps | grep /usr/local/bin/sbcl | awk '{print $1}'` ]]
then
    echo "emacs; slynk-stop-server"
    emacs; slynk-stop-server
else
    echo "##################################################"
    echo "SLYNK SERVER is NOT RUNNING"
    echo "##################################################"        
    echo "To start SLYNK SERVER in separate terminal invoke:"
    echo "slynk-start-server"
    echo "##################################################"
    echo "To start EMACS whis SLY invoke one of command:"
    echo "##################################################"    
    echo "slynk-emacs                    # when EMACS exiting SLYNK SERVER exiting to;"
    echo "emacs; slync-stop-server       # when EMACS exiting SLYNK SERVER exiting to;" 
    echo "emacs                          # when EMACS exiting SLYNK SERVER stay runing."
fi

# emacs; slynk-stop-server
# slynk-start-server

# Запускаем Emacs в фоновом режиме
# emacs &
# EMACS_PID=$!

# echo "EMACS_PID=${EMACS_PID}"

# Запускаем Slynk
# sbcl --dynamic-space-size 16384  --load /usr/local/bin/slynk-start-server.lisp
# SLYNK_PID=$!
# echo "SLYNK_PID=${SLYNK_PID}"
# Ждем завершения процесса Emacs

# wait $EMACS_PID
# После завершения Emacs останавливаем Slynk
# kill $SLYNK_PID

