#!/bin/bash

# Завершает процессы SBCL и ECL, запущенные как slynk-серверы

if [ "$1" == "all" ]; then
    echo "Останавливаю все slynk-серверы..."
    if [ "$(uname -o)" == "Msys" ]
    then
        kill $(ps | grep /usr/local/bin/sbcl| awk '{print $1}')
    else
        pkill -f "sbcl.*slynk-start-sbcl"
        pkill -f "ecl.*slynk-start-ecl"
    fi
elif [ "$1" == "sbcl" ]; then
    echo "Останавливаю slynk-серверы SBCL..."
    if [ "$(uname -o)" == "Msys" ]
    then
        kill $(ps | grep /usr/local/bin/sbcl| awk '{print $1}')
    else
        pkill -f "sbcl.*slynk-start-sbcl"
    fi
elif [ "$1" == "ecl" ]; then
    echo "Останавливаю slynk-серверы ECL..."
    if [ "$(uname -o)" == "Msys" ]
    then
        echo "Доступного slynk-сервера ECL под Msys пока нет"
        kill $(ps | grep /usr/local/bin/sbcl| awk '{print $1}')
    else
        pkill -f "ecl.*slynk-start-ecl"
    fi
else
    echo "Использование: $0 {all|sbcl|ecl}"
    exit 1
fi
