#!/bin/bash
#
# emacs &
# slynk-start-server

# Запускаем Emacs в фоновом режиме
emacs &
EMACS_PID=$!

echo "EMACS_PID=${EMACS_PID}"

# Запускаем Slynk
sbcl --dynamic-space-size 16384  --load /usr/local/bin/slynk-start-server.lisp
SLYNK_PID=$!
echo "SLYNK_PID=${SLYNK_PID}"
# Ждем завершения процесса Emacs

wait $EMACS_PID
# После завершения Emacs останавливаем Slynk
kill $SLYNK_PID

