#!/bin/bash
#

if [[ `ps | grep /usr/local/bin/sbcl | awk '{print $1}'` ]]
then
    echo "Slynk Is Running"
    echo "Starting EMACS ..."
    emacs
else
    echo "Slynk Is Not Running"
    echo "Starting EMACS & SLYNK ..." 
    emacs &
    screen-sbcl
fi
