* Подключение к удаленному лиспу
   
Одним из преимуществ SLIME заключается реализуется в том, что мы можем
легко запустить сторону Emacs (slime.el) на одной машине и LISP сервер
(swank) на другой.  Основная идея заключается в запуске Lisp на
удаленной машине, загрузке swank и ожидании входящих подключений от
SLIME.  На локальной машине мы запускаем Emacs и говорим SLIME
подключиться к удаленному компьютеру.  Подробностей несколько больше,
но основная описанная выше идея проста.

** Настройка образа Lisp на удаленном лисп-сервере

*** Запуск командного интерпретатора на удаленном сервере
#+begin_src sh
  ssh namatv@mnasoft-pi
#+end_src

*** Запуск screen
#+begin_src sh
  screen -R
#+end_src

*** Запуск лисп (ccl)
#+begin_src sh
  ccl
#+end_src

**** Запуск серверной части SWANK
#+begin_src lisp
  (require 'asdf)
  (asdf:oos 'asdf:load-op 'swank)
  (setf swank:*use-dedicated-output-stream* nil)
  (swank:create-server :port 4005  :dont-close t)
#+end_src

*** Выход из screen
C-a d

*** Выход из интерпретатора команд
$C-d

** Машина с Emacs
*** Создание тоннеля
#+begin_src sh
  ssh -2 -N -f -L 4005:localhost:4005 namatv@mnasoft-pi
#+end_src

*** Запуск emacs
#+begin_src sh
  emacs
#+end_src

**** Подключение к удаленному серверу
#+begin_src elisp
  (slime-connect "localhost" 4005)
#+end_src
